name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 2.0.0-mb.22
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

module:
  androidX: true
environment:
  sdk: ">=2.15.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_api_headers: ^3.1.0
  google_maps_flutter: ^2.5.0
  flutter_google_maps_webservices: ^1.1.1
  http: any
  location: ^5.0.3
  provider: ^6.1.1
  tuple: ^2.0.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
 - /example/lib/keys.dart
 - /example/android/app/src/main/AndroidManifest.xml
 - /example/ios/Runner/AppDelegate.swift
